specfile_path: tools/fedora/dbcsr.spec
files_to_sync:
  - src: tools/fedora/
    dest: ./
    delete: true
    filters:
      - "protect .git*"
      - "protect sources"
      - "protect changelog"
      - "- plans/rpminspect"
      - "- plans/rpmlint"
      # No packaged tmt jobs described yet, removing the .fmf as well
      - "- .fmf/"
  - .packit.yaml
upstream_package_name: dbcsr
downstream_package_name: dbcsr
upstream_tag_template: v{version}

targets:
  - fedora-all-x86_64
  - fedora-all-aarch64

jobs:
  - &copr_build
    job: copr_build
    trigger: release
    owner: lecris
    project: release
  - <<: *copr_build
    trigger: commit
    branch: master
    project: nightly
    update_release: true
  - &tests
    job: tests
    trigger: commit
    fmf_path: tools/fedora
  - job: copr_build
    trigger: pull_request
  - <<: *tests
    trigger: pull_request
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
